# Exported from:        http://host.docker.internal:5516/
# Release version:      26.1.0-322.130

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: AI Tasks Demo
spec:
- template: Tasks for README screenshots
  scheduledStartDate: 2026-04-02T09:31:10.437Z
  dueDate: 2026-04-02T10:31:10.437Z
  phases:
  - phase: Examples
    tasks:
    - name: Report failed releases
      type: community-llm.LlmAgent
      description: Use an agent to automate your workflow
      capabilities:
      - remote
      prompt: |-
        Create a ticket for each failed release.

        Use the issue list in xebialabs-community/community-release-llm-integration
      model: Anthropic Sonnet 4.5
      mcpServer1: Release MCP Server
      mcpServer2: GitHub MCP Server
    - name: Say hello
      type: community-llm.LlmPrompt
      capabilities:
      - remote
      prompt: Say hello in 6 languages for 6 continents
      model: Amazon Nova Micro 1:0
    - name: Interactive chat
      type: community-llm.LlmChat
      capabilities:
      - remote
      model: Gemini 2.5 Flash
    - name: Read GitHub issue
      type: community-llm.McpCallTool
      description: Read issue number `1` from GitHub repo **community-release-llm-integration**
      capabilities:
      - remote
      server: GitHub MCP Server
      tool: issue_read
      input: |-
        {
        "issue_number": 1,
        "method": "get",
        "owner": "xebialabs-community",
        "repo": "community-release-llm-integration"
        }
      result: "${issue}"
    - name: List Release MCP tools
      type: community-llm.McpListToolsTask
      description: Lists all MCP tools for this Release server
      capabilities:
      - remote
      server: Release MCP Server
    color: "#3d6c9e"
  variables:
  - type: xlrelease.StringVariable
    key: issue
    requiresValue: false
    showOnReleaseStart: false
    label: Issue
    description: The issue json from GitHub
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_Tasks_for_README_screenshots_scriptUserPassword"
  riskProfile: Default risk profile
