# Exported from:        http://host.docker.internal:5516/
# Release version:      26.1.0-322.130

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: AI Tasks Demo
spec:
- template: 1. MCP examples
  description: "Demo template to show different uses of the **MCP: Call tool** task."
  scheduledStartDate: 2026-04-02T09:31:10.186Z
  dueDate: 2026-04-02T10:31:10.186Z
  phases:
  - phase: Call tool
    tasks:
    - name: "Release: List folders"
      type: community-llm.McpCallTool
      capabilities:
      - remote
      server: Release MCP Server
      tool: list_folders
      input: |-
        {
          "request": {}
        }
    - name: "GitHub: Get my details"
      type: community-llm.McpCallTool
      capabilities:
      - remote
      server: GitHub MCP Server
      tool: get_me
    - name: "GitHub: Read sample issue"
      type: community-llm.McpCallTool
      capabilities:
      - remote
      server: GitHub MCP Server
      tool: issue_read
      input: |-
        {
        "issue_number": 1,
        "method": "get",
        "owner": "xebialabs-community",
        "repo": "community-release-llm-integration"
        }
      result: "${issue}"
    color: "#3d6c9e"
  variables:
  - type: xlrelease.StringVariable
    key: issue
    requiresValue: false
    showOnReleaseStart: false
    label: Issue
    description: The issue json from GitHub
  riskProfile: Default risk profile
