---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: AI Demo
spec:

  # MCP Servers
  - name: Agility MCP Server
    type: community-llm.McpServer
    url: https://api.staging.digital.ai/agilitymcp/v1/mcp
    headers:
      X-Agility-Bearer: !value AGILITY_KEY
      X-Agility-Host: https://www7.v1host.com/V1Production

  - name: Release MCP Server
    type: community-llm.McpServer
    url: http://host.docker.internal:8000/mcp

  - name: GitHub MCP Server
    type: community-llm.McpServer
    url: https://api.githubcopilot.com/mcp/
    headers:
        Authorization: !value GITHUB_TOKEN

    # AI Models
  - name: Gemini 2.5 Pro
    type: community-llm.GeminiModel
    apiKey: !value GEMINI_API_KEY
    model_id: gemini-2.5-pro

  - name: Gemini 2.5 Flash
    type: community-llm.GeminiModel
    apiKey: !value GEMINI_API_KEY
    model_id: gemini-2.5-flash

  - name: Gemini 2.5 Flash-Lite
    type: community-llm.GeminiModel
    apiKey: !value GEMINI_API_KEY
    model_id: gemini-2.5-flash-lite

  - name: Amazon Nova Micro 1:0
    type: community-llm.DaiLlmModel
    url: https://api.staging.digital.ai/llm
    apiKey: !value DAI_LLM_API_KEY
    model_id: amazon.nova-micro-v1:0

  - name: Anthropic Sonnet 4.5
    type: community-llm.DaiLlmModel
    url: https://api.staging.digital.ai/llm
    apiKey: !value DAI_LLM_API_KEY
    model_id: anthropic.claude-sonnet-4-5-20250929-v1:0

  - name: OpenAI GPT 5
    type: community-llm.OpenAiModel
    apiKey: !value OPENAI_API_KEY
    model_id: gpt-5

  - name: OpenAI GPT 5 mini
    type: community-llm.OpenAiModel
    apiKey: !value OPENAI_API_KEY
    model_id: gpt-5-mini

  - name: OpenAI GPT 5 nano
    type: community-llm.OpenAiModel
    apiKey: !value OPENAI_API_KEY
    model_id: gpt-5-nano

  # Demo Templates
  - template: MCP Agility Sample
    phases:
      - phase: MCP
        tasks:
          - name: List Agility tools
            type: community-llm.McpListToolsTask
            server: Agility MCP Server
          - name: Get current Agility user
            type: community-llm.McpCallTool
            server: Agility MCP Server
            tool: get_current_user
          - name: OK?
            type: xlrelease.GateTask
            owner: admin

  - template: MCP Release Sample
    phases:
      - phase: List releases
        tasks:
          - name: List Release tools
            type: community-llm.McpListToolsTask
            server: Release MCP Server
          - name: Get releases
            type: community-llm.McpCallTool
            server: Release MCP Server
            tool: list_releases
            input: |
              {
                "request": {}
              }
          - name: OK?
            type: xlrelease.GateTask
            owner: admin

  - template: List tools
    phases:
      - phase: List tools
        tasks:
          - name: List Release tools
            type: community-llm.McpListToolsTask
            server: Release MCP Server
          - name: List Agility Tools
            type: community-llm.McpListToolsTask
            server: Agility MCP Server
          - name: OK?
            type: xlrelease.GateTask
            owner: admin

  # Prompt examples

  - template: 2. Prompt example
    phases:
      - phase: Prompt
        tasks:
          - name: Say hello (Gemini)
            type: community-llm.LlmPrompt
            prompt: Say hello in six languages, one for each continent
            model: Gemini 2.5 Flash-Lite
          - name: Say hello (Amazon Nova)
            type: community-llm.LlmPrompt
            prompt: Say hello in six languages, one for each continent
            model: Amazon Nova Micro 1:0
          - name: Say hello (Anthropic)
            type: community-llm.LlmPrompt
            prompt: Say hello in six languages, one for each continent
            model: Anthropic Sonnet 4.5
          - name: Say hello (OpenAI)
            type: community-llm.LlmPrompt
            prompt: Say hello in six languages, one for each continent
            model: OpenAI GPT 5 nano
          - name: OK?
            type: xlrelease.GateTask
            owner: admin

  # Full example
  - template: 1. Agility summarize user
    phases:
      - phase: User details
        tasks:
          - name: Get current Agility user
            type: community-llm.McpCallTool
            variableMapping:
              result: "${user}"
            server: Agility MCP Server
            tool: get_current_user
          - name: Get name
            type: community-llm.LlmPrompt
            variableMapping:
              response: "${name}"
            model: Gemini 2.5 Flash
            prompt: |-
              Extract the name from the following data. Give me only the full name as a result
              
              ```
              ${user}
              ```
          - name: Get summary
            type: community-llm.LlmPrompt
            variableMapping:
              response: "${summary}"
            model: Gemini 2.5 Flash
            prompt: |-
              Please create a nice summary of the following data
              
              ```
              ${user}
              ```
          - name: Summary for ${name}
            type: xlrelease.Task
            description: ${summary}
    variables:
      - type: xlrelease.StringVariable
        key: user
        requiresValue: false
        showOnReleaseStart: false
        label: User info
        description: JSON info of user
      - type: xlrelease.StringVariable
        key: summary
        requiresValue: false
        showOnReleaseStart: false
        label: User summary
        description: The response from Google Gemini
      - type: xlrelease.StringVariable
        key: name
        requiresValue: false
        showOnReleaseStart: false
        label: User name
        description: Subject of the message.

  # Langchain example

  - template: 3. Release Agent demo
    phases:
      - phase: Report
        tasks:
          - name: Fix last failed release
            type: community-llm.LlmAgent
            prompt: |
              Create a GitHub issue to fix the last failed release in xebialabs-community/community-release-llm-integration repo. 
              
              Cause: Jenkins ran out of space
              Root cause: Builds take too long
            model: Gemini 2.5 Flash
            mcpServer1: GitHub MCP Server
          - name: OK?
            type: xlrelease.GateTask
            owner: admin


  - template: 4. Chat example
    phases:
      - phase: Prompt
        tasks:
          - name: Chat with agent
            type: community-llm.LlmChat
            model: Amazon Nova Micro 1:0
          - name: OK?
            type: xlrelease.GateTask
            owner: admin
    scriptUsername: admin
    scriptUserPassword: admin

  - template: Read GitHub issue
    phases:
    - phase: Read issue
      tasks:
      - name: Read sample issue
        type: community-llm.McpCallTool
        server: GitHub MCP Server
        tool: issue_read
        input: |-
          {
          "issue_number": 1,
          "method": "get",
          "owner": "xebialabs-community",
          "repo": "community-release-llm-integration"
          }
        result: ${issue}
      - name: Check issue
        type: xlrelease.GateTask
        description: |-
          # Issue found
  
          ```
          ${issue}
          ```
      color: "#3d6c9e"
    variables:
    - type: xlrelease.StringVariable
      key: issue
      requiresValue: false
      showOnReleaseStart: false
      label: Issue
      description: The issue json from GitHub

  - template: Tasks for README screenshots
    variables:
      - type: xlrelease.StringVariable
        key: issue
        requiresValue: false
        showOnReleaseStart: false
        label: Issue
        description: The issue json from GitHub
    scriptUsername: admin
    scriptUserPassword: admin
    phases:
      - phase: Examples
        color: "#3d6c9e"
        tasks:
          - name: Report failed releases
            type: community-llm.LlmAgent
            description: Use an agent to automate your workflow
            prompt: |-
              Create a ticket for each failed release.
              
              Use the issue list in xebialabs-community/community-release-llm-integration
            model: Anthropic Sonnet 4.5
            mcpServer1: Release MCP Server
            mcpServer2: GitHub MCP Server

          - name: Say hello
            type: community-llm.LlmPrompt
            prompt: Say hello in 6 languages for 6 continents
            model: Amazon Nova Micro 1:0

          - name: Interactive chat
            type: community-llm.LlmChat
            model: Gemini 2.5 Flash

          - name: Read GitHub issue
            type: community-llm.McpCallTool
            description: Read issue number `1` from GitHub repo **community-release-llm-integration**
            result: ${issue}
            server: GitHub MCP Server
            tool: issue_read
            input: |-
              {
              "issue_number": 1,
              "method": "get",
              "owner": "xebialabs-community",
              "repo": "community-release-llm-integration"
              }

          - name: List Release MCP tools
            type: community-llm.McpListToolsTask
            description: Lists all MCP tools for this Release server
            server: Release MCP Server

